name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Run unit tests
        run: dotnet test tests/Messentra.UnitTests/Messentra.UnitTests.csproj -r linux-x64

      - name: Run component tests
        run: dotnet test tests/Messentra.ComponentTests/Messentra.ComponentTests.csproj -r linux-x64

